# Generated by Django 3.2.6 on 2022-06-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Укажите, активен ли аккаунт', verbose_name='Аккаунт активен'),
        ),
    ]
